from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from datetime import datetime
import logging

from database import get_db, User, EmailCampaign
from schemas import EmailAutomationRequest, EmailAutomationResponse, SendEmailRequest
from auth_routes import get_current_user

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/email", tags=["Email Automation"])

# ==================== GENERATE EMAIL ====================

@router.post("/generate", response_model=EmailAutomationResponse)
def generate_email(
    request: EmailAutomationRequest,
    current_user: User = Depends(get_current_user)
):
    """
    Generate a personalized cold email for recruiter.
    """
    
    try:
        # Prepare skills text
        skills_text = ", ".join(request.user_skills[:5]) if request.user_skills else "relevant skills"
        
        # Generate email body
        email_body = f"""Hi {request.recruiter_name},

I hope this email finds you well. I'm reaching out because I'm very interested in the {request.job_title} position at {request.company_name}.

With my background in {skills_text}, I believe I can make a meaningful contribution to your team and help drive success for your organization.

I've attached my resume for your reference and would love to discuss how my skills and experience align with your needs.

Thank you for considering my application. I look forward to hearing from you.

Best regards,
{request.user_name}"""
        
        subject = f"Application for {request.job_title} Position at {request.company_name}"
        
        logger.info(f"Email generated by {current_user.email} for {request.recruiter_email}")
        
        return EmailAutomationResponse(
            email_body=email_body,
            subject=subject
        )
    
    except Exception as e:
        logger.error(f"Email generation error: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to generate email")

# ==================== SEND EMAIL ====================

@router.post("/send", response_model=dict)
def send_email(
    request: SendEmailRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Send cold email to recruiter and log in database.
    
    In production, integrate with:
    - SendGrid
    - AWS SES
    - Mailgun
    - Gmail API
    """
    
    try:
        # Validate email
        if not request.recruiter_email or '@' not in request.recruiter_email:
            raise HTTPException(status_code=400, detail="Invalid recruiter email")
        
        # Generate email content
        skills_text = ", ".join(request.user_skills[:5]) if request.user_skills else "relevant skills"
        
        email_body = f"""Hi {request.recruiter_name},

I hope this email finds you well. I'm reaching out because I'm very interested in the {request.job_title} position at {request.company_name}.

With my background in {skills_text}, I believe I can make a meaningful contribution to your team and help drive success for your organization.

I've attached my resume for your reference and would love to discuss how my skills and experience align with your needs.

Thank you for considering my application. I look forward to hearing from you.

Best regards,
{request.user_name}"""
        
        subject = f"Application for {request.job_title} Position at {request.company_name}"
        
        # ==================== EMAIL SENDING LOGIC ====================
        # For production, replace this with actual email service
        # Options:
        # 1. SendGrid: pip install sendgrid
        # 2. AWS SES: pip install boto3
        # 3. Gmail API: pip install google-auth-oauthlib
        # 4. Twilio SendGrid: pip install twilio-sendgrid
        
        send_success = send_email_via_service(
            recipient_email=request.recruiter_email,
            subject=subject,
            body=email_body
        )
        
        if not send_success:
            raise HTTPException(status_code=500, detail="Failed to send email")
        
        # Log email campaign in database
        campaign = EmailCampaign(
            user_id=current_user.id,
            recruiter_email=request.recruiter_email,
            email_body=email_body
        )
        db.add(campaign)
        db.commit()
        
        logger.info(f"Email sent by {current_user.email} to {request.recruiter_email}")
        
        return {
            'success': True,
            'message': f'Email sent successfully to {request.recruiter_email}',
            'subject': subject,
            'recruiter_email': request.recruiter_email,
            'sent_at': datetime.utcnow().isoformat()
        }
    
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        logger.error(f"Email sending error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to send email: {str(e)}")

# ==================== EMAIL SERVICE INTEGRATION ====================

def send_email_via_service(recipient_email: str, subject: str, body: str) -> bool:
    """
    Send email using configured email service.
    
    Current implementation: DEMO MODE (logs instead of sending)
    
    To enable real email sending, uncomment the service you want to use:
    """
    
    # ==================== OPTION 1: SENDGRID ====================
    # from sendgrid import SendGridAPIClient
    # from sendgrid.helpers.mail import Mail
    # 
    # try:
    #     message = Mail(
    #         from_email='noreply@jobify.com',
    #         to_emails=recipient_email,
    #         subject=subject,
    #         plain_text_content=body
    #     )
    #     sg = SendGridAPIClient(os.getenv('SENDGRID_API_KEY'))
    #     response = sg.send(message)
    #     return response.status_code == 202
    # except Exception as e:
    #     logger.error(f"SendGrid error: {str(e)}")
    #     return False
    
    # ==================== OPTION 2: GMAIL API ====================
    # import base64
    # from google.auth.transport.requests import Request
    # from google.oauth2.service_account import Credentials
    # from google.api_core import retry
    # 
    # try:
    #     # Setup Gmail API
    #     SCOPES = ['https://www.googleapis.com/auth/gmail.send']
    #     creds = Credentials.from_service_account_file(
    #         'credentials.json', scopes=SCOPES
    #     )
    #     
    #     # Create message
    #     message = {
    #         'raw': base64.urlsafe_b64encode(
    #             f"From: your-email@gmail.com\n"
    #             f"To: {recipient_email}\n"
    #             f"Subject: {subject}\n\n"
    #             f"{body}".encode()
    #         ).decode()
    #     }
    #     
    #     # Send email
    #     from google.googleapis.discovery import build
    #     service = build('gmail', 'v1', credentials=creds)
    #     result = service.users().messages().send(userId='me', body=message).execute()
    #     return True
    # except Exception as e:
    #     logger.error(f"Gmail API error: {str(e)}")
    #     return False
    
    # ==================== OPTION 3: AWS SES ====================
    # import boto3
    # 
    # try:
    #     client = boto3.client('ses', region_name='us-east-1')
    #     response = client.send_email(
    #         Source='noreply@jobify.com',
    #         Destination={'ToAddresses': [recipient_email]},
    #         Message={
    #             'Subject': {'Data': subject},
    #             'Body': {'Text': {'Data': body}}
    #         }
    #     )
    #     return True
    # except Exception as e:
    #     logger.error(f"AWS SES error: {str(e)}")
    #     return False
    
    # ==================== OPTION 4: TWILIO SENDGRID ====================
    # from twilio.rest import Client
    # 
    # try:
    #     account_sid = os.getenv('TWILIO_ACCOUNT_SID')
    #     auth_token = os.getenv('TWILIO_AUTH_TOKEN')
    #     client = Client(account_sid, auth_token)
    #     
    #     message = client.messages.create(
    #         from_='noreply@jobify.com',
    #         body=body,
    #         to=recipient_email
    #     )
    #     return True
    # except Exception as e:
    #     logger.error(f"Twilio error: {str(e)}")
    #     return False
    
    # ==================== DEMO MODE (Development) ====================
    # Log email to console/logs instead of sending
    logger.info(f"[DEMO MODE] Email would be sent to {recipient_email}")
    logger.info(f"Subject: {subject}")
    logger.info(f"Body:\n{body}")
    
    # In production, implement one of the email services above
    return True

# ==================== GET EMAIL CAMPAIGNS ====================

@router.get("/campaigns")
def get_email_campaigns(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get user's email campaigns.
    """
    
    campaigns = db.query(EmailCampaign).filter(
        EmailCampaign.user_id == current_user.id
    ).limit(50).all()
    
    return {
        'total_campaigns': len(campaigns),
        'campaigns': [
            {
                'id': c.id,
                'recruiter_email': c.recruiter_email,
                'sent_date': c.sent_date,
                'opened': c.opened,
                'replied': c.replied
            }
            for c in campaigns
        ]
    }

# ==================== UPDATE CAMPAIGN STATUS ====================

@router.put("/campaigns/{campaign_id}")
def update_campaign_status(
    campaign_id: int,
    opened: bool = None,
    replied: bool = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Update campaign status (opened, replied).
    """
    
    try:
        campaign = db.query(EmailCampaign).filter(
            EmailCampaign.id == campaign_id,
            EmailCampaign.user_id == current_user.id
        ).first()
        
        if not campaign:
            raise HTTPException(status_code=404, detail="Campaign not found")
        
        if opened is not None:
            campaign.opened = opened
        
        if replied is not None:
            campaign.replied = replied
        
        db.commit()
        
        logger.info(f"Campaign {campaign_id} status updated")
        
        return {
            'success': True,
            'message': 'Campaign status updated',
            'campaign_id': campaign_id
        }
    
    except Exception as e:
        db.rollback()
        logger.error(f"Campaign update error: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to update campaign")

# ==================== EMAIL TEMPLATES ====================

@router.get("/templates")
def get_email_templates():
    """
    Get predefined email templates.
    """
    
    templates = {
        'professional': {
            'name': 'Professional',
            'subject': 'Application for {job_title} Position at {company_name}',
            'body': '''Hi {recruiter_name},

I hope this email finds you well. I'm reaching out because I'm very interested in the {job_title} position at {company_name}.

With my background in {skills}, I believe I can make a meaningful contribution to your team.

I've attached my resume for your reference.

Best regards,
{user_name}'''
        },
        'casual': {
            'name': 'Casual',
            'subject': 'Interested in {job_title} at {company_name}',
            'body': '''Hey {recruiter_name},

I came across the {job_title} position at {company_name} and I'm really interested!

I have experience with {skills} and would love to learn more about the role.

Feel free to check out my resume below.

Cheers,
{user_name}'''
        },
        'detailed': {
            'name': 'Detailed',
            'subject': 'Application for {job_title} - {user_name}',
            'body': '''Dear {recruiter_name},

Thank you for considering my application for the {job_title} position at {company_name}.

I am a passionate developer with expertise in {skills}. Throughout my career, I have successfully delivered projects that demonstrate my technical depth and commitment to excellence.

I am confident that my skills and experience align perfectly with your team's needs, and I would welcome the opportunity to discuss how I can contribute to {company_name}'s success.

My resume is attached for your review. I look forward to speaking with you soon.

Sincerely,
{user_name}'''
        }
    }
    
    return templates